### ISSUE TITLE
not working with vim-latex

### ISSUE THREAD

**Issue by rfabbri** [zhou13/vim-easyescape#2]
When opening latex files, the 'jk' maps don't work.

**Comment by zhou13** [comment]
'jk' map works for me when opening latex files.  Maybe your other latex plugins override that map for you?

**Comment by rfabbri** [comment]
I wrote a work-around in vim-latex for this, see: https://github.com/vim-latex/vim-latex/issues/111
vim-latex has a mapping for `` `k ``  (tex leader followed by k), and also identity mappings for `` `j `` that are in place since vim-latex uses IMAP for mapping, to map the largest string for similar endings. These conflict with easyescape's suggested mappings.
