### ISSUE TITLE
Indenting in Python files

### ISSUE THREAD

**Issue by kuator** [zhou13/vim-easyescape#3]
After pressing kj cursor goes to the beginning of line
![another](https://user-images.githubusercontent.com/25168308/52144206-db1c0d80-2687-11e9-9908-334b518cfb06.gif)
And that's normal behavior
But after I installed plugin it doesn't do this
![gif](https://user-images.githubusercontent.com/25168308/52144278-0868bb80-2688-11e9-858a-c08ed5ef5d6a.gif)

**Comment by zhou13** [comment]
This seems to be a "bug" in vim. If you type `x<BS><Esc>` on an empty line you still get the same behavior. Not sure I should work around it in the plugin or fix it in vim.

**Comment by fatjing** [comment]
Please work around it.

`:h autoindent`
> Copy indent from current line when starting a new line (typing \<CR> in Insert mode or when using the "o" or "O" command). If you do not type anything on the new line except \<BS> or CTRL-D and then type \<Esc>, CTRL-O or \<CR>, the indent is deleted again.

Please preserve this behavior.

[vim-easyescape-plus](https://github.com/hyhugh/vim-easyescape-plus) seems to have a workaround and a nice feature keeping the buf status as unmodified if nothing modified. But unfortunately it doesn't map jk kj simultaneously.

**Comment by zhou13** [comment]
Thank you for the infomation. However, I am not sure how to  preserve this behavior. I take a look at vim-easyescape-plus. It will insert a `c-w` if current only contains `<space>`. This might be less annoying than the current solution, but it is still not the ideal behavior of `autoindent`.

**Comment by zhou13** [comment]
I push my workaround. Let me know if it is better.

**Comment by fatjing** [comment]
It is better now. Thank you.
How about reverting the modified buffer status? Entering insert mode and doing nothing, a true \<Esc> brings back to normal mode with everything intact, while this plugin leaves the buffer modified.

**Comment by aselker** [comment]
The workaround works great for me!  But, it also overwrites the unnamed buffer with whatever whitespace got deleted.  Would it be easy to send the whitespace to "_ to avoid that?

Thanks!

Edit: looks like you got that too, thank you!

**Comment by aselker** [comment]
One lingering problem: after deleting the whitespace, the "." command repeats the delete.  Is it possible to run a command without overwriting the . buffer?

**Comment by zhou13** [comment]
I am not sure how to do that since according to the definition of ".", it repeats the *last change*.  This might be possible with https://github.com/tpope/vim-repeat, but I am not really familiar with it.

**Comment by zhou13** [comment]
Since the original question is partially solved, I will close this issue. Let me know if you have better ideas.
