### ISSUE TITLE
Is it possible to only map kj and not jk?

### ISSUE THREAD

**Issue by hwalinga** [zhou13/vim-easyescape#5]
I only want to escape with kj and not with jk. Would that be possible using your method?

**Comment by zhou13** [comment]
This plugin currently does not support it. It is possible to implement it but I don't think I will work on this. Fork and PR are already welcome :)

**Comment by jdhao** [comment]
@hwalinga I have implemented a similar plugin to escape insert mode without lagging. You can define your own keys to leave insert mode. The plugin is [here](https://github.com/jdhao/better-escape.vim). You may give it a try to see if it works well for you.
